apiVersion: v1
kind: Service
metadata:
  name: analise-lotofacil
spec:
  type: NodePort
  selector:
    app: analise-lotofacil
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081